name: build
on:
  push:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.3.0
      - run: |
          docker run -i hadolint/hadolint < Dockerfile

  build:
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: koenighotze/multi-trivy
          tags: |
            type=semver,pattern={{raw}}
            type=sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          install: true
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 110 # Berlin
          format: "YYYY-MM-DD-HH-mm-ss"
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            NAME=koenighotze/multi-trivy
            DESCRIPTION=Run trivy on docker-compose files
            VERSION=${{ steps.docker_meta.outputs.version }}
            COMMIT_SHA=${{ github.sha }}
            BUILD_TIMESTAMP=${{ steps.time.outputs.time }}
            VCS_URL=${{ github.repository }}
